---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: forgejo-http.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3000