#!/usr/bin/env python3
import click
import os
import subprocess


class Handler:
    def __init__(self):
        self.KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")

    def disable(self, ns, *args, **kwargs):
        """Remove addon from kubernetes"""

        cmd = [
            "/bin/sh",
            "-c",
            f"{self.KUBECTL} get all -n {ns} -o yaml | {self.KUBECTL} delete -f -",
        ]
        try:
            subprocess.check_call(cmd)
        except Exception as e:
            click.echo(e)
            
        cmd = ["/bin/sh", "-c", f"{self.KUBECTL} delete namespace {ns}"]
        try:
            subprocess.check_call(cmd)
        except Exception as e:
            click.echo(e)


@click.command()
@click.option("--ns", default="groupeffect", help="delete custom kubernetes namespace")
def main(ns):
    click.echo(f"Disabling groupeffect in namespace {ns}")
    H = Handler()
    H.disable(ns="runner")
    H.disable(ns=ns)
    H.disable(ns="forgejo")


if __name__ == "__main__":
    main()
